import {test,expect,type WebSocketRoute} from '@playwright/test';
import {readFileSync} from 'node:fs';
const manifest=JSON.parse(readFileSync(new URL('../../cms/packages/resources/interactive-models/cuboid-volume-01/manifest.json',import.meta.url),'utf8'));

test('model stays visible as questions scroll, rotates, and backend can unpin it',async({page})=>{
  let socket:WebSocketRoute;
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.route('**/api/models/**',route=>route.fulfill({json:manifest}));
  await page.routeWebSocket('**/layout-test',ws=>{socket=ws;});
  await page.goto('/');
  await page.getByRole('button',{name:'Start learning'}).click();
  await page.getByLabel('Tutor address').fill('ws://127.0.0.1:32004/layout-test');
  await page.getByRole('button',{name:'Connect to tutor',exact:true}).click();
  await expect(page.locator('.connection')).toContainText('Connected');
  const send=(event:unknown)=>socket!.send(JSON.stringify(event));
  send({type:'model3d',content:'cuboid-volume-01',attrs:{action:'build-base',position:'160,80'}});
  const model=page.locator('[data-model="cuboid-volume-01"]');
  await expect(model).toHaveAttribute('data-count','12');
  await expect(page.locator('.tl-shape[data-shape-type="model3d"] [data-model]')).toHaveCount(1);
  await expect(page.locator('.model-dock')).toHaveCount(0);
  const initial=await model.boundingBox();
  send({type:'text_chunk',content:'4 × 3 = 12 cubes in one layer',attrs:{position:'760,120'}});
  send({type:'ask',content:'There are two layers. How many cubes will fill the whole cuboid?',attrs:{position:'760,220'}});
  const question=page.locator('.tl-shape[data-shape-type="text"]').filter({hasText:'Q. There are two layers.'});
  await expect(question).toBeVisible();
  const explanation=page.locator('.tl-shape[data-shape-type="text"]').filter({hasText:'4 × 3'});
  await expect.poll(async()=>{const q=await question.boundingBox(),w=await explanation.boundingBox();return q!.y-(w!.y+w!.height);}).toBeGreaterThan(20);
  await expect.poll(async()=>{const q=await question.boundingBox();return q!.x;}).toBeGreaterThan(initial!.x+initial!.width);
  await page.screenshot({path:'artifacts/model-question.png'});
  // A simple canvas click must not disable teaching follow.
  await page.mouse.click(1100,700);
  await expect(page.getByRole('button',{name:'Back to the lesson'})).toHaveCount(0);
  send({type:'text_chunk',content:'Volume = length × width × height',attrs:{position:'160,1500'}});
  const later=page.locator('.tl-shape[data-shape-type="text"]').filter({hasText:'Volume ='});
  await expect(later).toBeVisible();
  await expect.poll(async()=>{const b=await later.boundingBox();return b!.y+b!.height;}).toBeLessThan(800);
  await expect.poll(async()=>Math.abs((await model.boundingBox())!.y-initial!.y)).toBeLessThan(2);
  const current=await model.boundingBox();
  const gap=(await later.boundingBox())!.x-(current!.x+current!.width);
  expect(gap).toBeGreaterThan(10);expect(gap).toBeLessThan(65);
  await page.getByRole('button',{name:'Select (V)',exact:true}).click();
  const polygon=model.locator('polygon').first(),before=await polygon.getAttribute('points');
  await page.screenshot({path:'artifacts/model-before-rotate.png'});
  await expect(page.locator('.tl-hit-test-blocker')).not.toBeVisible();
  await page.mouse.move(current!.x+current!.width*.5,current!.y+current!.height*.5);
  await page.mouse.down();await page.mouse.move(current!.x+current!.width*.7,current!.y+current!.height*.5,{steps:8});await page.mouse.up();
  await expect(polygon).not.toHaveAttribute('points',before!);
  await page.screenshot({path:'artifacts/model-docked.png'});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(async()=>{const b=await model.boundingBox();return b!.x+b!.width;}).toBeLessThan(391);
  await expect.poll(async()=>{const b=await later.boundingBox();return b!.x+b!.width;}).toBeLessThan(391);
  await expect.poll(async()=>{const b=await later.boundingBox();return b!.y+b!.height;}).toBeLessThan(650);
  await page.screenshot({path:'artifacts/model-docked-mobile.png'});
  send({type:'model3d',content:'cuboid-volume-01',attrs:{action:'remove'}});
  await expect(model).toHaveCount(1);
  send({type:'text_chunk',content:'Now we continue below the model.',attrs:{}});
  const below=page.locator('.tl-shape[data-shape-type="text"]').filter({hasText:'Now we continue'});
  await expect(below).toBeVisible();
  await expect.poll(async()=>{const m=(await model.boundingBox())!,t=(await below.boundingBox())!;return t.y-m.y-m.height;}).toBeGreaterThan(0);
  await expect(page.locator('.canvas-area')).not.toHaveClass(/with-model/);
  expect(errors).toEqual([]);
});
