import {useEffect,useState} from 'react';
import {ArrowRight,Check} from 'lucide-react';
import {request,type Classroom} from './api';
import {getHome,type LearningHome,type NextLearning} from './learning';
// Missing CMS titles can contain imported IDs; never show these as headings.
function heading(value?:string){return value&&!/^(?:x[0-9a-f]+:|[0-9a-f]{24}$)/i.test(value)?value:undefined;}
export default function StudentLearning({studentId,revision,busy,start,classes}:{classes:Classroom[];studentId:string;revision:number;busy:boolean;start:(topicId:string,next?:Extract<NextLearning,{status:'continue'}>)=>void}){
  const [classId,setClassId]=useState(''),[allowed,setAllowed]=useState<string[]|null>(null),[classError,setClassError]=useState('');
  useEffect(()=>{let active=true;setAllowed(null);setClassError('');if(classId)request<{topics:{topicId:string}[]}>(`/students/${encodeURIComponent(studentId)}/classes/${encodeURIComponent(classId)}/topics`).then(r=>{if(active)setAllowed(r.topics.map(t=>t.topicId));}).catch(e=>{if(active)setClassError(e.message);});return()=>{active=false;};},[classId,studentId,revision]);
  const [home,setHome]=useState<LearningHome|null>(null),[error,setError]=useState(''),[subject,setSubject]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{let active=true;setHome(null);setError('');getHome(studentId).then(h=>{if(active){setHome(h);setSubject(old=>h.subjects.some(s=>s.subjectId===old)?old:h.subjects[0]?.subjectId??'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[studentId,revision,retry]);
  if(error)return <div className="j-error" role="alert">Your topics couldn’t be loaded. {error}<button className="j-link" onClick={()=>setRetry(v=>v+1)}>Try again</button></div>;
  if(!home)return <p role="status">Loading your topics…</p>;
  const selected=home.subjects.find(s=>s.subjectId===subject),current=selected?{...selected,topics:selected.topics.filter(t=>!classId||allowed?.includes(t.topicId))}:undefined,continuation=home.continueWith?.resumeSessionId?home.continueWith:null;
  const title=home.subjects.flatMap(s=>s.topics).find(t=>t.topicId===continuation?.topicId)?.title;
  return <section className="j-student-learning">{continuation&&<div className="j-continue"><div><small>Pick up where you left off</small><h2>{title??'Your learning'}</h2><p>{['clarity','mastering'].includes(continuation.state)?'Practise ':''}{continuation.conceptTitle??'Your lesson'}</p></div><button className="j-primary" disabled={busy} onClick={()=>start(continuation.topicId,continuation)}>Continue <ArrowRight size={17}/></button></div>}
    <div className="j-learning-filter">{classes.length>1&&<label>Topics from<select aria-label="Topics from" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">All my classes</option>{classes.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>}</div>{classError&&<p role="alert">{classError}</p>}<div className="j-subject-tabs" role="tablist" aria-label="Subjects">{home.subjects.map(s=><button role="tab" aria-selected={subject===s.subjectId} key={s.subjectId} onClick={()=>setSubject(s.subjectId)}>{s.title}</button>)}</div>
    <div className="j-topic-list" role="tabpanel" aria-label={current?.title??'Topics'}>{!home.subjects.length?<div className="j-empty"><h2>Your learning space is ready.</h2><p>Your topics will appear here when your parent or teacher has chosen them.</p><button className="j-secondary" onClick={()=>setRetry(v=>v+1)}>Refresh topics</button></div>:classId&&!allowed&&!classError?<p role="status">Loading class topics…</p>:!current?.topics.length?<p>No topics assigned for this subject yet.</p>:current.topics.map((t,i)=>{const previous=current.topics[i-1];return <div key={t.topicId}>{(i===0||previous.strandTitle!==t.strandTitle||previous.unitTitle!==t.unitTitle)&&<p className="j-topic-group">{[heading(t.strandTitle),heading(t.unitTitle)].filter(Boolean).join(' · ')}</p>}<article className="j-topic-row"><div><h3>{t.title}</h3><small>{t.status==='completed'?'Completed':t.status==='in_progress'?`In progress${t.next?.conceptTitle?' · '+(t.next.resumeSessionId?'Pick up: ':'Next: ')+(['clarity','mastering'].includes(t.next.state)?'Practise ':'')+t.next.conceptTitle:''}`:t.status==='unavailable'?(t.reason??'Not available yet'):'Ready to explore'}</small></div>{t.status==='completed'?<span className="j-complete"><Check size={18}/> Complete</span>:<button className="j-secondary" disabled={busy||t.status==='unavailable'||(t.status==='in_progress'&&!t.next)} onClick={()=>start(t.topicId)}>{t.status==='in_progress'?'Continue':'Let’s start'}<ArrowRight size={16}/></button>}</article></div>;})}</div></section>;
}
